<a href="https://colab.research.google.com/github/sanjay-MGR/Machine-Learning-basic-/blob/main/classification_with_Logistic_Regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#mport laiberies
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,confusion_matrix

In [ ]:
#load datasets
data = sns.load_dataset('titanic')
data.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False


In [ ]:
df1 = data[['survived','age','fare']]

In [ ]:
df1.head(2)

,survived,age,fare
0,0,22.0,7.2500
1,1,38.0,71.2833


In [ ]:
df1.isna().sum() #check null value

,0
survived,0
age,177
fare,0


In [ ]:
df1.shape

(891, 3)

In [ ]:
df1['age'] = df1['age'].fillna(df1['age'].mean()) #fill the null value of age with its mean or average age

/tmp/ipykernel_7748/3647070331.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['age'] = df1['age'].fillna(df1['age'].mean()) #fill the null value of age with its mean or average age


In [ ]:
df1.isna().sum()

,0
survived,0
age,0
fare,0


In [ ]:
df1


,survived,age,fare
0,0,22.000000,7.2500
1,1,38.000000,71.2833
2,1,26.000000,7.9250
3,1,35.000000,53.1000
4,0,35.000000,8.0500
...,...,...,...
886,0,27.000000,13.0000
887,1,19.000000,30.0000
888,0,29.699118,23.4500
889,1,26.000000,30.0000


In [ ]:
#split data into x and y
x = df1.drop('survived',axis = 1)

In [ ]:
x.head(2)

,age,fare
0,22.0,7.2500
1,38.0,71.2833


In [ ]:
y = df1['survived']
y.head(4)

,survived
0,0
1,1
2,1
3,1


In [ ]:
#model built
LR = LogisticRegression()
LR

LogisticRegression()

In [ ]:
#fit the model
LR.fit(x,y)

LogisticRegression()

In [ ]:
#predict the value
y_pred = LR.predict(x)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,

In [ ]:
#check the accuracy,recall,precision,cnfucion matrix ,recall
acs = accuracy_score(y,y_pred)
acs

0.6565656565656566

In [ ]:
#recall
reacall = recall_score(y,y_pred)
round(reacall,2)


0.23

In [ ]:
#percision
pas = precision_score(y,y_pred)
pas

In [ ]:
#f1_score
f1 = f1_score(y,y_pred)
f1

0.34334763948497854

In [ ]:
#confuion matrix
cm = confusion_matrix(y,y_pred)#[tp,fn,fp,tn]
cm

array([[505,  44],
       [262,  80]])

In [ ]:
# multiple Classification with Logistic Regression
#Load data set
data_new = sns.load_dataset('penguins')

In [ ]:
data_new

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female


In [ ]:
data_new = data_new.drop(['island','sex'],axis = 1)

In [ ]:
data_new.isna().sum()

,0
species,0
bill_length_mm,2
bill_depth_mm,2
flipper_length_mm,2
body_mass_g,2


In [ ]:
#handel or fill the null values with there mean
data_new['bill_length_mm'] = data_new['bill_length_mm'].fillna(data_new['bill_length_mm'].mean())
data_new['bill_depth_mm'] = data_new['bill_depth_mm'].fillna(data_new['bill_depth_mm'].mean())
data_new['flipper_length_mm'] = data_new['flipper_length_mm'].fillna(data_new['flipper_length_mm'].mean())
data_new['body_mass_g'] = data_new['body_mass_g'].fillna(data_new['body_mass_g'].mean())

In [ ]:
data_new.isna().sum()

,0
species,0
bill_length_mm,0
bill_depth_mm,0
flipper_length_mm,0
body_mass_g,0


In [ ]:
#split data into a and b
a = data_new.drop('species',axis = 1)
a.head(2)

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
0,39.1,18.7,181.0,3750.0
1,39.5,17.4,186.0,3800.0


In [ ]:
b = data_new['species']
b.head(2)

,species
0,Adelie
1,Adelie


In [ ]:
#build the model
multiple_lr = LogisticRegression(max_iter=1000)
multiple_lr

LogisticRegression(max_iter=1000)

In [ ]:
# train or fit the model
multiple_lr.fit(a,b)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

In [ ]:
# predict the value
y_predrr =multiple_lr.predict(a)
y_predrr

array(['Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie',
       'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adelie', 'Adel

In [ ]:
output = pd.DataFrame(y_predr,columns = ['Output'])

In [ ]:
output.head(10)

,Output
0,Adelie
1,Adelie
2,Adelie
3,Adelie
4,Adelie
5,Adelie
6,Adelie
7,Adelie
8,Adelie
9,Adelie


In [ ]:
# check accuracy
accuracy_sc  = accuracy_score(b,y_predrr)
accuracy_sc

0.9941860465116279

In [ ]:
#confucion matrix
conf_mat = confusion_matrix(b,y_predrr)
conf_mat

array([[152,   0,   0],
       [  1,  67,   0],
       [  1,   0, 123]])

In [ ]:
from google.colab import files

In [ ]:
uplode_file = files.upload()

Saving creditcard.csv to creditcard.csv
